"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MaterialUIControllerProvider } from 'context'

import { ThemeProvider } from "@mui/material/styles";
import theme from "assets/theme";

import NavBar from "layouts/sidenavbar"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <MaterialUIControllerProvider>
      <ThemeProvider theme={theme}>
        <NavBar/>
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </MaterialUIControllerProvider>
    </html>
  );
}
